CREATE TABLE Orders (
    OrderId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newid()),
    OrderCost DECIMAL(18, 2) NOT NULL,
    DeliveryFee DECIMAL(18, 2) NOT NULL,
    Weight DECIMAL(18, 2) NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Status INT NOT NULL,
    CONSTRAINT FK_UserId FOREIGN KEY (UserId) REFERENCES Users(Id),
);

CREATE TABLE Order_Product (
	OrderId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProductId UNIQUEIDENTIFIER NOT NULL,
	Amount INT NOT NULL,
	ProductsCost INT NOT NULL,
	DeliveryDate DATE NOT NULL,
	CONSTRAINT FK_OrderId FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
	CONSTRAINT FK_ProductId FOREIGN KEY (ProductId) References Products(Id),
);

ALTER TABLE Orders
ADD OrderDate DATETIME DEFAULT GETDATE() NOT NULL; 