USE BMT_database
CREATE TABLE [dbo].[Order] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (newid()),
	[UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Users](Id),
    [DeliveryDate] DATE NOT NULL,
	[State] INT NOT NULL
);

CREATE TABLE [dbo].[PedidoItems] (
    [OrderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Order](Id),
    [ProductId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Products](Id),
    [Cantidad] INT NOT NULL,
    PRIMARY KEY (OrderId, ProductId)
);